### ISSUE TITLE
All requests sending back text request param

### ISSUE THREAD

**Issue by brockoffdev** [ellisonleao/slack-howdoi#2]
Error 

```
Please type a ?text= param
```

Receiving this on all Slack requests.  Running on our micro server on AWS.

**Comment by ellisonleao** [comment]
I will check that! Thanks for reporting

**Comment by ellisonleao** [comment]
hey @brockoffdev how your integration is configured? 
Are you using `https://slack-howdoi.herokuapp.com/howdoi` as the URL ? I just tested here and it's working.

You can test the requests results with the cURL command:

```
curl -X POST https://slack-howdoi.herokuapp.com/howdoi?text=open+file+in+python
```

Please let me know if you followed the integration steps https://github.com/ellisonleao/slack-howdoi#integrate-with-your-team

Thanks!

**Comment by ellisonleao** [comment]
Hey @brockoffdev i just reproduced the issue and just fixed it on https://github.com/ellisonleao/slack-howdoi/commit/d4eac448d74cd4a89e55bf4e5cf8a4dba28b823d . It's fixed now
